main/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from .views import AskLinkList, LinkList, LinkCreate, LinkDetail, CommentList,\
RssFeed, AtomFeed


urlpatterns = patterns("",
    url("^$",
        LinkList.as_view(),
        name="home"),
    url("^new/$",
        LinkList.as_view(), {"by_score": False},
        name="link_list_latest"),
    url("^ask/$",
        AskLinkList.as_view(),
        name="link_list_ask"),
    url("^comments/$",
        CommentList.as_view(), {"by_score": False},
        name="comment_list_latest"),
    url("^best/$",
        CommentList.as_view(),
        name="comment_list_best"),
    url("^link/create/$",
        login_required(LinkCreate.as_view()),
        name="link_create"),
    # url("^link/(?P<slug>.*)/$",
    # changing to pk so that users can leave link field blank to ask questions
    url("^link/(?P<pk>\d+)/$",
        LinkDetail.as_view(),
        name="link_detail"),
    url("^users/(?P<username>.*)/links/$",
        LinkList.as_view(), {"by_score": False},
        name="link_list_user"),
    url("^users/(?P<username>.*)/links/$",
        LinkList.as_view(), {"by_score": False},
        name="link_list_user"),
    url("^users/(?P<username>.*)/comments/$",
        CommentList.as_view(), {"by_score": False},
        name="comment_list_user"),

    # Feeds
    url(r"^rss/$", RssFeed()),
    url(r"^atom/$", AtomFeed()),
    
    # Robots
    url(r"^robots\.txt$", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()


urlpatterns = patterns("",
    ("^admin/", include(admin.site.urls)),
    ("^", include("main.urls")),
    ("^", include("mezzanine.urls")),
)

urlpatterns += patterns("",
    (r"^browserid/", include("django_browserid.urls")), # =persona
)

# Adds ``STATIC_URL`` to the context.
handler500 = "mezzanine.core.views.server_error"

main/models.py
from time import time
from datetime import datetime
from urlparse import urlparse

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from mezzanine.core.models import Displayable, Ownable
from mezzanine.generic.models import Rating
from mezzanine.generic.fields import RatingField, CommentsField

# from mezzanine.core.managers import SearchableManager

class Link(Displayable, Ownable):

    link = models.URLField(blank=True)
    rating = RatingField()
    comments = CommentsField()
    
    # objects = SearchableManager()
    # search_fields = ("title", "description")

    @models.permalink
    def get_absolute_url(self):
        return ("link_detail", (), {"pk": self.pk})

    def domain(self):
        return urlparse(self.link).netloc


class Profile(models.Model):

    user = models.OneToOneField("auth.User")
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    karma = models.IntegerField(default=0, editable=False)

    def __unicode__(self):
        return "%s (%s)" % (self.user, self.karma)


@receiver(post_save, sender=Rating)
def karma(sender, **kwargs):
    """
    Each time a rating is saved, check its value and modify the
    profile karma for the related object's user accordingly.
    Since ratings are either +1/-1, if a rating is being edited,
    we can assume that the existing rating is in the other direction,
    so we multiply the karma modifier by 2.
    """
    rating = kwargs["instance"]
    value = int(rating.value)
    if not kwargs["created"]:
        value *= 2
    content_object = rating.content_object
    if rating.user != content_object.user:
        queryset = Profile.objects.filter(user=content_object.user)
        queryset.update(karma=models.F("karma") + value)











# https://docs.djangoproject.com/en/dev/topics/auth/customizing/#a-full-example
# from django.db import models
# from django.contrib.auth.models import (
#     BaseUserManager, AbstractBaseUser
# )
# 
# 
# class ProfileManager(BaseUserManager):
#     def create_user(self, email, password=None):
#         """
#         Creates and saves a User with the given email and password.
#         """
#         if not email:
#             raise ValueError('Users must have an email address')
# 
#         user = self.model(
#             email=self.normalize_email(email),
#             date_of_birth=date_of_birth,
#         )
# 
#         user.set_unusable_password(password)
#         user.save(using=self._db)
#         return user
# 
#     def create_superuser(self, email, date_of_birth, password):
#         """
#         Creates and saves a superuser with the given email, date of
#         birth and password.
#         """
#         user = self.create_user(email,
#             password=password
#         )
#         user.is_admin = True
#         user.save(using=self._db)
#         return user
# 
# 
# class Profile(AbstractBaseUser):
#     email = models.EmailField(
#                         verbose_name='email address',
#                         max_length=255
#                     )
#     user = models.OneToOneField("auth.User")
#     website = models.URLField(blank=True)
#     bio = models.TextField(blank=True)
#     karma = models.IntegerField(default=0, editable=False)
#     is_active = models.BooleanField(default=True)
#     is_admin = models.BooleanField(default=False)
#     
#     objects = ProfileManager()
#     
#     # USERNAME_FIELD = 'email'
#     # REQUIRED_FIELDS = ['date_of_birth']
#     
#     def get_full_name(self):
#         # The user is identified by their email address
#         return self.email
# 
#     def get_short_name(self):
#         # The user is identified by their email address
#         return self.email
# 
#     # On Python 3: def __str__(self):
#     def __unicode__(self):
#         return self.email
# 
#     def has_perm(self, perm, obj=None):
#         "Does the user have a specific permission?"
#         # Simplest possible answer: Yes, always
#         return True
# 
#     def has_module_perms(self, app_label):
#         "Does the user have permissions to view the app `app_label`?"
#         # Simplest possible answer: Yes, always
#         return True
# 
#     @property
#     def is_staff(self):
#         "Is the user a member of staff?"
#         # Simplest possible answer: All admins are staff
#         return self.is_admin
# 
#     def __unicode__(self):
#         return "%s (%s)" % (self.user, self.karma)

main/forms.py
# from django import forms
# from mezzanine.accounts.forms import ProfileForm
# from .models import Profile
# from django.contrib.auth.models import User
# 
# class MyProfileForm(ProfileForm):       
#     class Meta:
#         # fields = ['username', 'website', 'bio']
#         # exclude = {'password1', 'password2'}
#         widgets = {
#             'password1': forms.HiddenInput(),
#             'password1': forms.HiddenInput()
#         }
#         
#     def __init__(self, *args, **kwargs):
#         super(ProfileForm, self).__init__(*args, **kwargs)
#         del self.fields['password1']
#         del self.fields['password2']
# 
# 
# 
# # =todo: http://djangosnippets.org/snippets/1301/

main/views.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.contrib.messages import info, error
from django.forms.models import modelform_factory
from django.shortcuts import get_object_or_404, redirect
from django.utils.timezone import now
from django.contrib.syndication.views import Feed
from django.utils.feedgenerator import Atom1Feed
from django.views.generic import ListView, CreateView, DetailView

from mezzanine.conf import settings
from mezzanine.generic.models import ThreadedComment
from mezzanine.utils.views import paginate

from .models import Link
from .utils import order_by_score


class UserFilterView(ListView):
    """
    List view that puts a ``profile_user`` variable into the context,
    which is optionally retrieved by a ``username`` urlpattern var.
    If a user is loaded, ``object_list`` is filtered by the loaded
    user. Used for showing lists of links and comments.
    """

    def get_context_data(self, **kwargs):
        context = super(UserFilterView, self).get_context_data(**kwargs)
        try:
            username = self.kwargs["username"]
        except KeyError:
            profile_user = None
        else:
            users = User.objects.select_related("profile")
            lookup = {"username__iexact": username, "is_active": True}
            profile_user = get_object_or_404(users, **lookup)
            qs = context["object_list"].filter(user=profile_user)
            context["object_list"] = qs
        context["profile_user"] = profile_user
        context["no_data"] = ("None yet.")
        return context


class ScoreOrderingView(UserFilterView):
    """
    List view that optionally orders ``object_list`` by calculated
    score. Subclasses must defined a ``date_field`` attribute for the
    related model, that's used to determine time-scaled scoring.
    Ordering by score is the default behaviour, but can be
    overridden by passing ``False`` to the ``by_score`` arg in
    urlpatterns, in which case ``object_list`` is sorted by most
    recent, using the ``date_field`` attribute. Used for showing lists
    of links and comments.
    """

    def get_context_data(self, **kwargs):
        context = super(ScoreOrderingView, self).get_context_data(**kwargs)
        qs = context["object_list"]
        context["by_score"] = self.kwargs.get("by_score", True)
        if context["by_score"]:
            qs = order_by_score(qs, self.score_fields, self.date_field)
        else:
            qs = qs.order_by("-" + self.date_field)
        context["object_list"] = paginate(qs, self.request.GET.get("page", 1),
            settings.ITEMS_PER_PAGE, settings.MAX_PAGING_LINKS)
        context["title"] = self.get_title(context)
        return context


class LinkView(object):
    """
    List and detail view mixin for links - just defines the correct
    queryset.
    """
    def get_queryset(self):
        return Link.objects.published().select_related("user", "user__profile")


class LinkList(LinkView, ScoreOrderingView):
    """
    List view for links, which can be for all users (homepage) or
    a single user (links from user's profile page). Links can be
    order by score (homepage, profile links) or by most recently
    created ("new" main nav item).
    """

    date_field = "publish_date"
    score_fields = ("rating_sum", "comments_count")

    def get_title(self, context):
        if context["by_score"]:
            return ""  # Homepage
        if context["profile_user"]:
            return "Links by %s " % context["profile_user"].profile
        else:
            return "Newest Links"


# =todo: refactor into LinkList view =============
class AskLinkView(object):
    """
    View for Links with the link field blank, used for 'Ask FN:'
    Questions. =todo: We can probably refactor this into the LinkList view.
    """
    def get_queryset(self):
        return Link.objects.published().filter(link='').select_related("user", "user__profile")

# =todo: refactor into LinkList view =============
class AskLinkList(AskLinkView, ScoreOrderingView):
    """
    View for Links with the link field blank, used for 'Ask FN:'
    Questions. =todo: We can probably refactor this into the LinkList view.
    """

    date_field = "publish_date"
    score_fields = ("rating_sum", "comments_count")

    def get_title(self, context):
        return "Questions"

        

class LinkCreate(CreateView):
    """
    Link creation view - assigns the user to the new link, as well
    as setting Mezzanine's ``gen_description`` attribute to ``False``,
    so that we can provide our own descriptions.
    """

    form_class = modelform_factory(Link, fields=("title", "link",
                                                 "description"))
    model = Link

    def form_valid(self, form):
        hours = getattr(settings, "ALLOWED_DUPLICATE_LINK_HOURS", None)
        
        # Changed permalinks to pk instead of slug
        # so users can leave the URL field blank and ask questions,
        # so we need to check whether the link field is blank before
        # doing the check for duplicate links.
        if form.instance.link:
            
            if hours:
                lookup = {
                    "link": form.instance.link,
                    "publish_date__gt": now() - timedelta(hours=hours),
                }
                try:
                    link = Link.objects.get(**lookup)
                except Link.DoesNotExist:
                    pass            
                else:
                    error(self.request, "Link exists")
                    return redirect(link)
        form.instance.user = self.request.user
        form.instance.gen_description = False
        info(self.request, "Entry created")
        return super(LinkCreate, self).form_valid(form)
    
    # variables for post to food news bookmarklet
    def get_context_data(self, **kwargs):
        context = super(LinkCreate, self).get_context_data(**kwargs)
        context['u'] = self.request.GET.get('u', '')
        context['t'] = self.request.GET.get('t', '')
        return context


class LinkDetail(LinkView, DetailView):
    """
    Link detail view - threaded comments and rating are implemented
    in its template.
    """
    pass


class CommentList(ScoreOrderingView):
    """
    List view for comments, which can be for all users ("comments" and
    "best" main nav items) or a single user (comments from user's
    profile page). Comments can be order by score ("best" main nav item)
    or by most recently created ("comments" main nav item, profile
    comments).
    """

    date_field = "submit_date"
    score_fields = ("rating_sum",)

    def get_queryset(self):
        return ThreadedComment.objects.visible().select_related("user",
            "user__profile").prefetch_related("content_object")

    def get_title(self, context):
        if context["profile_user"]:
            return "Comments by %s" % context["profile_user"].profile
        elif context["by_score"]:
            return "Best Comments"
        else:
            return "Latest Comments"


# =feeds ===================================

class RssFeed(Feed):
    title = "Food News"
    link = "http://food.hypertexthero.com"
    description = "Links about healthy sustainable food, ranked by readers."
    # description_template = "hth/feed_description.html" # using default for now

    def items(self):
        return Link.objects.filter(status=2).order_by('-publish_date')[:30]

    def item_title(self, item):
        return item.title

    def item_pubdate(self, item):
        return item.publish_date

    def item_description(self, item):
        # return smart_truncate(item.body_html)
        return item.description

class AtomFeed(RssFeed):
    feed_type = Atom1Feed
    subtitle = RssFeed.description

main/templates/accounts/account_form.html
{% extends "base.html" %}
{% load i18n mezzanine_tags %}

{% block meta_title %}{{ title }}{% endblock %}
{% block title %}{{ title }}{% endblock %}
{% block body_id %}account{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li>{{ title }}</li>
{% endblock %}

{% block main %}
<fieldset>
  <legend>{{ title }}</legend>
  <form method="post"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
    {# {% fields_for form %} #}

    {% csrf_token %}
    <input name="referrer" value="//{{request.META.HTTP_HOST}}/users/{{request.user}}/" type="hidden">
    
    {{ form.non_field_errors }}
    
    <div class="control-group input_id_username">
      {{ form.username.errors }}
      <label class="control-label" for="id_username">
        {{ form.username.label }}
      </label>
      <div class="controls">
          <input autofocus="" id="id_username" maxlength="30" name="username" required="" value="{{ form.username.value }}" type="text">
          <span class="help-inline">Only letters, numbers, dashes or underscores please.</span>
      </div>
    </div>
    
    <div class="control-group input_id_website ">
      {{ form.website.errors }}
      <label class="control-label" for="id_website">
        {{ form.website.label }}
      </label>
      <div class="controls">
        <input id="id_website" maxlength="200" name="website" type="text" value="{{ form.website.value|default:'' }}" />
        <span class="help-inline"></span>
      </div>
    </div>
    
    <div class="control-group input_id_bio">
      {{ form.bio.errors }}
      <label class="control-label" for="id_bio">
        {{ form.bio.label }}
      </label>
      <div class="controls">
        <textarea cols="40" id="id_bio" name="bio" rows="10">{{ form.bio.value|default:'' }}</textarea>
        <span class="help-inline"></span>
      </div>
    </div>

    <div class="form-actions">
      <input class="btn btn-primary btn-large" type="submit" value="{{ title }}"> or <a href="javascript:history.go(-1)">Cancel</a>
    </div>
  </form>
</fieldset>
{% endblock %}

main/templates/accounts/account_login.html
{% extends "accounts/account_form.html" %}
{% load i18n future browserid mezzanine_tags %}

{% block main %}

{% if request.user.is_authenticated %}
    <p>You are already logged in.</p>
{% else %}

    {# {{ block.super }} #}
    {# {% url "signup" as signup_url %} #}
    {# <p>{% blocktrans with request.GET.next as next %}<a href="{{ signup_url }}?next={{ next }}">Don&rsquo;t have an account?</a>{% endblocktrans %}</p> #}
    {# {% url "mezzanine_password_reset" as password_reset_url %} #}
    {# {% url "profile_update" as profile_update_url %} #}
    {# {% blocktrans %}<p><a href="{{ password_reset_url }}?next={{ profile_update_url }}">Forgot your password?</a></p>{% endblocktrans %}</p> #}

    {% nevercache %}
    {% if request.path == "/accounts/login/" %}
    <p>{% browserid_login text='Login' next='/rating/' link_class='btn btn-custom' %}</p>
    {% else %}
    <p>{% browserid_login text='Login' link_class='btn btn-custom' %}</p>
    {% endif %}
    {% endnevercache %}
    
{% endif %}

{% endblock %}

main/templates/accounts/account_profile.html
{% extends "base.html" %}
{% load i18n future mezzanine_tags %}

{% block meta_title %}{{ profile_user.username }}{% endblock %}
{% block title %}{{ profile_user.profile.user }}{% endblock %}
{% block body_id %}account{% endblock %}

{% block main %}
    <dl class="dl-horizontal">
      <dt>Member Since</dt> 
      <dd>{{ profile_user.date_joined|date:"j F Y" }}</dd>
      <dt>Karma</dt> 
      <dd>{{ profile_user.profile.karma }} <a id="karma" class="small normal" data-content="Karma is a measure of reputation on {{ settings.SITE_TITLE }}. It increases when a person&rsquo;s links or comments are upvoted." title="" data-toggle="popover" href="#" data-original-title="">what is this?</a></dd>
      {% with profile_user.profile as profile %}

      {% if profile.website %}
      <dt>Website</dt> 
      <dd>{{ profile.website|urlize }}</dd>
      {% endif %}
      
      {% if profile.bio %}
      <dt>Biography</dt>
      <dd>{{ profile.bio|urlize }}</dd>
      {% endif %}
      {% endwith %}

      <dt><a href="{% url "comment_list_user" profile_user.username %}">Comments</a></dt>
      <dd>{{ profile_user.comment_comments.count }}</dd>

      <dt><a href="{% url "link_list_user" profile_user.username %}">Links</a></dt>
      <dd>{{ profile_user.links.published.count }}</dd>
    </dl>
    

{% if profile_user == request.user %}
{# <div class="pull-right"> #}
    <p><a class="btn btn-large btn-primary btn-profile" href="{% url "profile_update" %}">Update profile</a></p>
{# </div> #}
{% endif %}
{% endblock %}

{% block extra_scripts %}
<script>
  $('#karma').popover()
</script>
{% endblock extra_scripts %}

main/templates/accounts/account_signup.html
{% extends "accounts/account_form.html" %}
{% load i18n %}

{% block main %}

{% if request.user.is_authenticated %}
    <p>{% trans "You're already logged in. If you'd like to create a new account, you'll need to log out first." %}</p>
{% else %}
    {{ block.super }}
    {% if settings.ACCOUNTS_VERIFICATION_REQUIRED %}
    <p>{% trans "After signing up, you'll receive an email with a link you need to click, in order to activate your account." %}</p>
    {% endif %}
{% endif %}

{% endblock %}